 * Running on http://127.0.0.1:3000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
127.0.0.1 - - [01/Apr/2018 15:36:57] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/shiyanlou/SYL/infomation_site/news/app.py", line 30, in index
    index_html = article()
  File "/home/shiyanlou/SYL/infomation_site/news/app.py", line 13, in __init__
    self.filename = os.listdir(self.file_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/home/shiyanlou/SYL/infomation_site/news/files'
127.0.0.1 - - [01/Apr/2018 15:36:57] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 15:36:57] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 15:36:57] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 15:36:58] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 15:36:58] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
127.0.0.1 - - [01/Apr/2018 15:41:22] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/shiyanlou/SYL/infomation_site/news/app.py", line 31, in index
    index_html = article()
  File "/home/shiyanlou/SYL/infomation_site/news/app.py", line 14, in __init__
    self.filename = os.listdir(self.file_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/home/shiyanlou/SYL/infomation_site/news/files'
127.0.0.1 - - [01/Apr/2018 15:41:22] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 15:41:22] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 15:41:22] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 15:41:27] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 15:41:27] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
127.0.0.1 - - [01/Apr/2018 15:42:07] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/shiyanlou/SYL/infomation_site/news/app.py", line 31, in index
    index_html = article()
  File "/home/shiyanlou/SYL/infomation_site/news/app.py", line 14, in __init__
    self.filename = os.listdir(self.file_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/home/shiyanlou/SYL/infomation_site/news..//files'
127.0.0.1 - - [01/Apr/2018 15:42:07] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 15:42:07] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 15:42:07] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 15:42:07] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 15:42:07] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
127.0.0.1 - - [01/Apr/2018 15:42:24] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/shiyanlou/SYL/infomation_site/news/app.py", line 33, in index
    return render_template('index.html', [contents[x] for x in range(len(contents))])
TypeError: render_template() takes 1 positional argument but 2 were given
127.0.0.1 - - [01/Apr/2018 15:42:24] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 15:42:24] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 15:42:24] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 15:42:25] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 15:42:25] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
127.0.0.1 - - [01/Apr/2018 15:42:48] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 15:42:48] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [01/Apr/2018 15:42:48] "GET /favicon.ico HTTP/1.1" 404 -
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
127.0.0.1 - - [01/Apr/2018 15:59:50] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 15:59:51] "GET / HTTP/1.1" 200 -
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
127.0.0.1 - - [01/Apr/2018 16:05:45] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 16:29:17] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 16:29:18] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 16:29:20] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 16:32:57] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 16:34:20] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 16:34:22] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 16:34:57] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 16:35:32] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 16:35:34] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 16:36:04] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 16:36:50] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 16:39:26] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 16:39:28] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 16:43:15] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 16:48:45] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 16:51:26] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 17:02:17] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 17:02:18] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 17:07:14] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/shiyanlou/SYL/infomation_site/news/app.py", line 33, in index
    return render_template('index.html',titles = index_html.get_title())
  File "/usr/local/lib/python3.5/dist-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/shiyanlou/SYL/infomation_site/news/templates/index.html", line 6, in template
    <p> {{ url_for('files', contends = 'title' }} </p>
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 896, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 878, in subparse
    rv = self.parse_statement()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 268, in parse_block
    node.body = self.parse_statements(('name:endblock',), drop_needle=True)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 878, in subparse
    rv = self.parse_statement()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 198, in parse_for
    body = self.parse_statements(('name:endfor', 'name:else'))
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 870, in subparse
    add_data(self.parse_tuple(with_condexpr=True))
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 615, in parse_tuple
    args.append(parse())
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 427, in parse_expression
    return self.parse_condexpr()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 432, in parse_condexpr
    expr1 = self.parse_or()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 445, in parse_or
    left = self.parse_and()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 454, in parse_and
    left = self.parse_not()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 465, in parse_not
    return self.parse_compare()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 469, in parse_compare
    expr = self.parse_math1()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 491, in parse_math1
    left = self.parse_concat()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 502, in parse_concat
    args = [self.parse_math2()]
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 512, in parse_math2
    left = self.parse_pow()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 523, in parse_pow
    left = self.parse_unary()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 542, in parse_unary
    node = self.parse_postfix(node)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 671, in parse_postfix
    node = self.parse_call(node)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 780, in parse_call
    value = self.parse_expression()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 427, in parse_expression
    return self.parse_condexpr()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 432, in parse_condexpr
    expr1 = self.parse_or()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 445, in parse_or
    left = self.parse_and()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 454, in parse_and
    left = self.parse_not()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 465, in parse_not
    return self.parse_compare()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 469, in parse_compare
    expr = self.parse_math1()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 491, in parse_math1
    left = self.parse_concat()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 502, in parse_concat
    args = [self.parse_math2()]
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 512, in parse_math2
    left = self.parse_pow()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 523, in parse_pow
    left = self.parse_unary()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 541, in parse_unary
    node = self.parse_primary()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 559, in parse_primary
    next(self.stream)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/lexer.py", line 361, in __next__
    self.current = next(self._iter)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/lexer.py", line 564, in wrap
    for lineno, token, value in stream:
  File "/usr/local/lib/python3.5/dist-packages/jinja2/lexer.py", line 688, in tokeniter
    filename)
jinja2.exceptions.TemplateSyntaxError: unexpected '}', expected ')'
127.0.0.1 - - [01/Apr/2018 17:07:14] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 17:07:14] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 17:07:14] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 17:07:20] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 17:07:51] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/shiyanlou/SYL/infomation_site/news/app.py", line 33, in index
    return render_template('index.html',titles = index_html.get_title())
  File "/usr/local/lib/python3.5/dist-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/usr/local/lib/python3.5/dist-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/shiyanlou/SYL/infomation_site/news/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/shiyanlou/SYL/infomation_site/news/templates/base.html", line 12, in top-level template code
    <div> {% block contend %} {% endblock %}</div>
  File "/home/shiyanlou/SYL/infomation_site/news/templates/index.html", line 6, in block "contend"
    <p> {{ url_for('files', contends = 'title') }} </p>
  File "/usr/local/lib/python3.5/dist-packages/flask/helpers.py", line 333, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1805, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/helpers.py", line 323, in url_for
    force_external=external)
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/routing.py", line 1768, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'files' with values ['contends']. Did you mean 'index' instead?
127.0.0.1 - - [01/Apr/2018 17:07:51] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 17:07:51] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 17:07:51] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 17:07:52] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
127.0.0.1 - - [01/Apr/2018 18:29:52] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/cli.py", line 184, in __call__
    self._flush_bg_loading_exception()
  File "/usr/local/lib/python3.5/dist-packages/flask/cli.py", line 172, in _flush_bg_loading_exception
    reraise(*exc_info)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/cli.py", line 161, in _load_app
    self._load_unlocked()
  File "/usr/local/lib/python3.5/dist-packages/flask/cli.py", line 176, in _load_unlocked
    self._app = rv = self.loader()
  File "/usr/local/lib/python3.5/dist-packages/flask/cli.py", line 237, in load_app
    rv = locate_app(self.app_import_path)
  File "/usr/local/lib/python3.5/dist-packages/flask/cli.py", line 90, in locate_app
    __import__(module)
File "/home/shiyanlou/SYL/infomation_site/news/app.py", line 36
    def file(filename)
                     ^
SyntaxError: invalid syntax
127.0.0.1 - - [01/Apr/2018 18:29:52] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 18:29:52] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 18:29:52] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 18:29:53] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 18:30:48] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/cli.py", line 189, in __call__
    rv = self._load_unlocked()
  File "/usr/local/lib/python3.5/dist-packages/flask/cli.py", line 176, in _load_unlocked
    self._app = rv = self.loader()
  File "/usr/local/lib/python3.5/dist-packages/flask/cli.py", line 237, in load_app
    rv = locate_app(self.app_import_path)
  File "/usr/local/lib/python3.5/dist-packages/flask/cli.py", line 90, in locate_app
    __import__(module)
File "/home/shiyanlou/SYL/infomation_site/news/app.py", line 29
    for i in
            ^
SyntaxError: invalid syntax
127.0.0.1 - - [01/Apr/2018 18:30:48] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 18:30:48] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 18:30:48] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 18:30:49] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 18:32:11] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 18:33:36] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 18:34:13] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 18:34:30] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 18:34:41] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 18:36:57] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/shiyanlou/SYL/infomation_site/news/app.py", line 32, in index
    return render_template('index.html',titles = index_html.get_title())
  File "/usr/local/lib/python3.5/dist-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/shiyanlou/SYL/infomation_site/news/templates/index.html", line 7, in template
    <p> {{ url_for('file', filename=title }} </p>
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 896, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 878, in subparse
    rv = self.parse_statement()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 268, in parse_block
    node.body = self.parse_statements(('name:endblock',), drop_needle=True)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 878, in subparse
    rv = self.parse_statement()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 198, in parse_for
    body = self.parse_statements(('name:endfor', 'name:else'))
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 870, in subparse
    add_data(self.parse_tuple(with_condexpr=True))
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 615, in parse_tuple
    args.append(parse())
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 427, in parse_expression
    return self.parse_condexpr()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 432, in parse_condexpr
    expr1 = self.parse_or()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 445, in parse_or
    left = self.parse_and()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 454, in parse_and
    left = self.parse_not()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 465, in parse_not
    return self.parse_compare()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 469, in parse_compare
    expr = self.parse_math1()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 491, in parse_math1
    left = self.parse_concat()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 502, in parse_concat
    args = [self.parse_math2()]
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 512, in parse_math2
    left = self.parse_pow()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 523, in parse_pow
    left = self.parse_unary()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 542, in parse_unary
    node = self.parse_postfix(node)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 671, in parse_postfix
    node = self.parse_call(node)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 780, in parse_call
    value = self.parse_expression()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 427, in parse_expression
    return self.parse_condexpr()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 432, in parse_condexpr
    expr1 = self.parse_or()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 445, in parse_or
    left = self.parse_and()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 454, in parse_and
    left = self.parse_not()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 465, in parse_not
    return self.parse_compare()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 469, in parse_compare
    expr = self.parse_math1()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 491, in parse_math1
    left = self.parse_concat()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 502, in parse_concat
    args = [self.parse_math2()]
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 512, in parse_math2
    left = self.parse_pow()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 523, in parse_pow
    left = self.parse_unary()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 541, in parse_unary
    node = self.parse_primary()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 557, in parse_primary
    next(self.stream)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/lexer.py", line 361, in __next__
    self.current = next(self._iter)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/lexer.py", line 564, in wrap
    for lineno, token, value in stream:
  File "/usr/local/lib/python3.5/dist-packages/jinja2/lexer.py", line 688, in tokeniter
    filename)
jinja2.exceptions.TemplateSyntaxError: unexpected '}', expected ')'
127.0.0.1 - - [01/Apr/2018 18:36:57] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 18:36:57] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 18:36:57] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 18:36:57] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 18:37:15] "GET / HTTP/1.1" 200 -
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
127.0.0.1 - - [01/Apr/2018 18:41:58] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/cli.py", line 184, in __call__
    self._flush_bg_loading_exception()
  File "/usr/local/lib/python3.5/dist-packages/flask/cli.py", line 172, in _flush_bg_loading_exception
    reraise(*exc_info)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/cli.py", line 161, in _load_app
    self._load_unlocked()
  File "/usr/local/lib/python3.5/dist-packages/flask/cli.py", line 176, in _load_unlocked
    self._app = rv = self.loader()
  File "/usr/local/lib/python3.5/dist-packages/flask/cli.py", line 237, in load_app
    rv = locate_app(self.app_import_path)
  File "/usr/local/lib/python3.5/dist-packages/flask/cli.py", line 100, in locate_app
    'ensure the extension is .py' % module)
flask.cli.NoAppException: The file/path provided (app) does not appear to exist.  Please verify the path is correct.  If app is not on PYTHONPATH, ensure the extension is .py
127.0.0.1 - - [01/Apr/2018 18:41:58] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 18:41:58] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 18:41:58] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 18:41:59] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 18:43:44] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 18:44:37] "GET / HTTP/1.1" 200 -
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
127.0.0.1 - - [01/Apr/2018 18:51:11] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 18:51:14] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 18:51:15] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 18:52:51] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 18:52:52] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 18:52:53] "GET / HTTP/1.1" 200 -
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
127.0.0.1 - - [01/Apr/2018 19:12:05] "GET /files/123 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/shiyanlou/SYL/infomation_site/news/app.py", line 37, in file
    if filename in files.self.filename():
AttributeError: 'article' object has no attribute 'self'
127.0.0.1 - - [01/Apr/2018 19:12:05] "GET /files/123?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:12:05] "GET /files/123?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:12:05] "GET /files/123?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:12:06] "GET /files/123?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:12:06] "GET /files/123?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
127.0.0.1 - - [01/Apr/2018 19:13:07] "GET /files/123 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/shiyanlou/SYL/infomation_site/news/app.py", line 37, in file
    if filename in files.filename():
TypeError: 'list' object is not callable
127.0.0.1 - - [01/Apr/2018 19:13:07] "GET /files/123?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:13:07] "GET /files/123?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:13:07] "GET /files/123?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:13:08] "GET /files/123?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:13:08] "GET /files/123?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
127.0.0.1 - - [01/Apr/2018 19:13:42] "GET /files/123 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/shiyanlou/SYL/infomation_site/news/app.py", line 37, in file
    if filename not in files.filename():
TypeError: 'list' object is not callable
127.0.0.1 - - [01/Apr/2018 19:13:42] "GET /files/123?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:13:42] "GET /files/123?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:13:42] "GET /files/123?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:13:42] "GET /files/123?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:13:43] "GET /files/123?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:13:44] "GET /files/123 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/shiyanlou/SYL/infomation_site/news/app.py", line 37, in file
    if filename not in files.filename():
TypeError: 'list' object is not callable
127.0.0.1 - - [01/Apr/2018 19:13:45] "GET /files/123?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:13:45] "GET /files/123?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:13:45] "GET /files/123?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:13:45] "GET /files/123?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:13:45] "GET /files/123?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
127.0.0.1 - - [01/Apr/2018 19:24:19] "GET /files/123 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/shiyanlou/SYL/infomation_site/news/app.py", line 39, in file
    if filename not in files.get_name():
  File "/home/shiyanlou/SYL/infomation_site/news/app.py", line 29, in get_name
    return [ self.get_json_content.keys()]
AttributeError: 'function' object has no attribute 'keys'
127.0.0.1 - - [01/Apr/2018 19:24:19] "GET /files/123?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:24:19] "GET /files/123?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:24:19] "GET /files/123?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:24:24] "GET /files/123?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:24:24] "GET /files/123?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
127.0.0.1 - - [01/Apr/2018 19:27:38] "GET /files/123 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/shiyanlou/SYL/infomation_site/news/app.py", line 39, in file
    if filename not in files.get_name():
  File "/home/shiyanlou/SYL/infomation_site/news/app.py", line 29, in get_name
    return [ self.get_json_content.keys()]
AttributeError: 'function' object has no attribute 'keys'
127.0.0.1 - - [01/Apr/2018 19:27:39] "GET /files/123?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:27:39] "GET /files/123?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:27:39] "GET /files/123?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:27:39] "GET /files/123?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:27:39] "GET /files/123?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:27:41] "GET /files/123 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/shiyanlou/SYL/infomation_site/news/app.py", line 39, in file
    if filename not in files.get_name():
  File "/home/shiyanlou/SYL/infomation_site/news/app.py", line 29, in get_name
    return [ self.get_json_content.keys()]
AttributeError: 'function' object has no attribute 'keys'
127.0.0.1 - - [01/Apr/2018 19:27:41] "GET /files/123?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:27:41] "GET /files/123?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:27:41] "GET /files/123?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:27:47] "GET /files/123?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:27:47] "GET /files/123?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
127.0.0.1 - - [01/Apr/2018 19:29:26] "GET /files/123 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/shiyanlou/SYL/infomation_site/news/app.py", line 36, in file
    if filename not in files.get_json_content.keys():
AttributeError: 'function' object has no attribute 'keys'
127.0.0.1 - - [01/Apr/2018 19:29:26] "GET /files/123?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:29:26] "GET /files/123?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:29:26] "GET /files/123?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:29:26] "GET /files/123?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:29:27] "GET /files/123?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
127.0.0.1 - - [01/Apr/2018 19:30:23] "GET /files/123 HTTP/1.1" 404 -
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
127.0.0.1 - - [01/Apr/2018 19:32:40] "GET /files/123 HTTP/1.1" 404 -
127.0.0.1 - - [01/Apr/2018 19:32:42] "GET /files/123 HTTP/1.1" 404 -
127.0.0.1 - - [01/Apr/2018 19:32:43] "GET /files/123 HTTP/1.1" 404 -
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
127.0.0.1 - - [01/Apr/2018 19:32:56] "GET /files/123 HTTP/1.1" 404 -
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
127.0.0.1 - - [01/Apr/2018 19:33:09] "GET /files/123 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/shiyanlou/SYL/infomation_site/news/app.py", line 38, in file
    abort(Response('404 Not found'))
NameError: name 'Response' is not defined
127.0.0.1 - - [01/Apr/2018 19:33:09] "GET /files/123?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:33:09] "GET /files/123?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:33:09] "GET /files/123?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:33:09] "GET /files/123?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:33:10] "GET /files/123?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
127.0.0.1 - - [01/Apr/2018 19:34:03] "GET /files/123 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/shiyanlou/SYL/infomation_site/news/app.py", line 38, in file
    abort(Response('404 Not found'))
NameError: name 'Response' is not defined
127.0.0.1 - - [01/Apr/2018 19:34:03] "GET /files/123?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:34:03] "GET /files/123?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:34:03] "GET /files/123?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:34:03] "GET /files/123?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:34:04] "GET /files/123?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:34:56] "GET /files/123 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/shiyanlou/SYL/infomation_site/news/app.py", line 38, in file
    abort(Response('404 Not found'))
NameError: name 'Response' is not defined
127.0.0.1 - - [01/Apr/2018 19:34:56] "GET /files/123?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:34:56] "GET /files/123?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:34:56] "GET /files/123?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:34:57] "GET /files/123?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:34:57] "GET /files/123?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
127.0.0.1 - - [01/Apr/2018 19:36:30] "GET /files/123 HTTP/1.1" 404 -
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
127.0.0.1 - - [01/Apr/2018 19:40:22] "GET /files/123 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/shiyanlou/SYL/infomation_site/news/app.py", line 39, in file
    return redirect(url_for('page_not_fount'))
NameError: name 'redirect' is not defined
127.0.0.1 - - [01/Apr/2018 19:40:22] "GET /files/123?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:40:22] "GET /files/123?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:40:22] "GET /files/123?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:40:27] "GET /files/123?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:40:27] "GET /files/123?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
127.0.0.1 - - [01/Apr/2018 19:40:51] "GET /files/123 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/shiyanlou/SYL/infomation_site/news/app.py", line 39, in file
    return redirect(url_for('page_not_fount'))
NameError: name 'url_for' is not defined
127.0.0.1 - - [01/Apr/2018 19:40:51] "GET /files/123?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:40:51] "GET /files/123?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:40:51] "GET /files/123?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:40:52] "GET /files/123?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:40:52] "GET /files/123?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
127.0.0.1 - - [01/Apr/2018 19:41:19] "GET /files/123 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/shiyanlou/SYL/infomation_site/news/app.py", line 39, in file
    return redirect(url_for('page_not_fount'))
  File "/usr/local/lib/python3.5/dist-packages/flask/helpers.py", line 333, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1805, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/helpers.py", line 323, in url_for
    force_external=external)
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/routing.py", line 1768, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'page_not_fount'. Did you mean 'static' instead?
127.0.0.1 - - [01/Apr/2018 19:41:19] "GET /files/123?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:41:19] "GET /files/123?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:41:19] "GET /files/123?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:41:19] "GET /files/123?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:41:20] "GET /files/123?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
127.0.0.1 - - [01/Apr/2018 19:41:56] "GET /files/123 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/shiyanlou/SYL/infomation_site/news/app.py", line 39, in file
    return redirect(url_for('page_not_fount',error = 404))
  File "/usr/local/lib/python3.5/dist-packages/flask/helpers.py", line 333, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1805, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/helpers.py", line 323, in url_for
    force_external=external)
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/routing.py", line 1768, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'page_not_fount' with values ['error']. Did you mean 'static' instead?
127.0.0.1 - - [01/Apr/2018 19:41:57] "GET /files/123?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:41:57] "GET /files/123?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:41:57] "GET /files/123?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:42:02] "GET /files/123?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:42:02] "GET /files/123?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
127.0.0.1 - - [01/Apr/2018 19:42:26] "GET /files/123 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/shiyanlou/SYL/infomation_site/news/app.py", line 39, in file
    return redirect(url_for('page_not_fount',error = 404))
  File "/usr/local/lib/python3.5/dist-packages/flask/helpers.py", line 333, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1805, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/helpers.py", line 323, in url_for
    force_external=external)
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/routing.py", line 1768, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'page_not_fount' with values ['error']. Did you mean 'static' instead?
127.0.0.1 - - [01/Apr/2018 19:42:27] "GET /files/123?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:42:27] "GET /files/123?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:42:27] "GET /files/123?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:42:32] "GET /files/123?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:42:32] "GET /files/123?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
127.0.0.1 - - [01/Apr/2018 19:49:30] "GET /files/123 HTTP/1.1" 404 -
127.0.0.1 - - [01/Apr/2018 19:51:41] "GET /files/123 HTTP/1.1" 404 -
127.0.0.1 - - [01/Apr/2018 19:52:23] "GET /files/helloworld HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/shiyanlou/SYL/infomation_site/news/app.py", line 40, in file
    return render_template('file.html',file = files.get_json_content(filename))
TypeError: get_json_content() takes 1 positional argument but 2 were given
127.0.0.1 - - [01/Apr/2018 19:52:24] "GET /files/helloworld?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:52:24] "GET /files/helloworld?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:52:24] "GET /files/helloworld?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:52:24] "GET /files/helloworld?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 19:52:24] "GET /files/helloworld?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
127.0.0.1 - - [01/Apr/2018 19:53:40] "GET /files/helloworld HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 20:00:21] "GET /files/helloworld HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 20:00:23] "GET /files/helloworld HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 20:01:28] "GET /files/helloworld HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 20:01:38] "GET /files/helloworld HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 20:02:25] "GET /files/helloworld HTTP/1.1" 200 -
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
127.0.0.1 - - [01/Apr/2018 20:17:54] "GET /files/helloworld HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 20:17:56] "GET /files/helloworld HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 20:19:18] "GET /files/helloworld HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 20:19:41] "GET /files/helloworld HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 20:19:54] "GET /files/helloworld HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 20:20:23] "GET /files/helloworld HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 20:20:47] "GET /files/helloworld HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 20:21:02] "GET /files/helloworld HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 20:21:03] "GET /files/helloworld HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 20:21:15] "GET /files/hello HTTP/1.1" 404 -
127.0.0.1 - - [01/Apr/2018 20:21:21] "GET /files/helloshiyanlou HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 20:21:27] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 20:21:28] "GET /files/helloshiyanlou HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 20:21:28] "GET /files/helloworld HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 20:21:28] "GET /nothing HTTP/1.1" 404 -
127.0.0.1 - - [01/Apr/2018 20:21:44] "GET /123 HTTP/1.1" 404 -
127.0.0.1 - - [01/Apr/2018 20:21:55] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 20:21:58] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 20:22:24] "GET /files/helloshiyanlou HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 20:22:57] "GET /files/helloshiyanlou HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 20:23:03] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 20:23:08] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 20:23:08] "GET /files/helloshiyanlou HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 20:23:08] "GET /files/helloworld HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 20:23:08] "GET /nothing HTTP/1.1" 404 -
127.0.0.1 - - [01/Apr/2018 20:23:56] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 20:23:59] "GET /123 HTTP/1.1" 404 -
127.0.0.1 - - [01/Apr/2018 20:24:02] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 20:24:02] "GET /files/helloshiyanlou HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 20:24:03] "GET /files/helloworld HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 20:24:03] "GET /nothing HTTP/1.1" 404 -
127.0.0.1 - - [01/Apr/2018 20:55:32] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 21:01:10] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/shiyanlou/SYL/infomation_site/news/app.py", line 31, in index
    return render_template('index.html',titles = index_html.get_title())
  File "/usr/local/lib/python3.5/dist-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/shiyanlou/SYL/infomation_site/news/templates/index.html", line 7, in template
    <h3> {{ url_for('file', filename = title }}</a></h3>
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 896, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 878, in subparse
    rv = self.parse_statement()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 268, in parse_block
    node.body = self.parse_statements(('name:endblock',), drop_needle=True)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 878, in subparse
    rv = self.parse_statement()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 198, in parse_for
    body = self.parse_statements(('name:endfor', 'name:else'))
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 870, in subparse
    add_data(self.parse_tuple(with_condexpr=True))
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 615, in parse_tuple
    args.append(parse())
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 427, in parse_expression
    return self.parse_condexpr()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 432, in parse_condexpr
    expr1 = self.parse_or()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 445, in parse_or
    left = self.parse_and()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 454, in parse_and
    left = self.parse_not()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 465, in parse_not
    return self.parse_compare()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 469, in parse_compare
    expr = self.parse_math1()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 491, in parse_math1
    left = self.parse_concat()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 502, in parse_concat
    args = [self.parse_math2()]
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 512, in parse_math2
    left = self.parse_pow()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 523, in parse_pow
    left = self.parse_unary()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 542, in parse_unary
    node = self.parse_postfix(node)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 671, in parse_postfix
    node = self.parse_call(node)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 780, in parse_call
    value = self.parse_expression()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 427, in parse_expression
    return self.parse_condexpr()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 432, in parse_condexpr
    expr1 = self.parse_or()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 445, in parse_or
    left = self.parse_and()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 454, in parse_and
    left = self.parse_not()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 465, in parse_not
    return self.parse_compare()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 469, in parse_compare
    expr = self.parse_math1()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 491, in parse_math1
    left = self.parse_concat()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 502, in parse_concat
    args = [self.parse_math2()]
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 512, in parse_math2
    left = self.parse_pow()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 523, in parse_pow
    left = self.parse_unary()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 541, in parse_unary
    node = self.parse_primary()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 557, in parse_primary
    next(self.stream)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/lexer.py", line 361, in __next__
    self.current = next(self._iter)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/lexer.py", line 564, in wrap
    for lineno, token, value in stream:
  File "/usr/local/lib/python3.5/dist-packages/jinja2/lexer.py", line 688, in tokeniter
    filename)
jinja2.exceptions.TemplateSyntaxError: unexpected '}', expected ')'
127.0.0.1 - - [01/Apr/2018 21:01:10] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 21:01:10] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 21:01:10] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 21:01:10] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 21:01:30] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 21:02:04] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 21:03:30] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 21:10:31] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 21:10:33] "GET /files/Hello%2C%20Shiyanlou%21 HTTP/1.1" 404 -
127.0.0.1 - - [01/Apr/2018 21:11:10] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 21:11:14] "GET /files/Hello%2C%20Shiyanlou%21 HTTP/1.1" 404 -
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
127.0.0.1 - - [01/Apr/2018 21:18:50] "GET /helloshiyanlou HTTP/1.1" 404 -
127.0.0.1 - - [01/Apr/2018 21:18:57] "GET /helloworld HTTP/1.1" 404 -
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
{'helloworld': {'title': 'Hello, World!', 'content': 'Hello world! \\\\n This is hello world demo page. \\\\n Please let us know if you have any questions \\\\n Thank you!', 'created_time': '2017-08-09 12:00:00'}, 'helloshiyanlou': {'title': 'Hello, Shiyanlou!', 'content': 'Welcome to shiyanlou.com \\n This is shiyanlou.com louplus demo page. \\n Please let us know if you have any questions \\n Thank you!', 'created_time': '2017-09-09 12:00:00'}}
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
127.0.0.1 - - [01/Apr/2018 21:21:58] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/shiyanlou/SYL/infomation_site/news/app.py", line 32, in index
    return render_template('index.html',titles = file.get_title())
AttributeError: 'function' object has no attribute 'get_title'
127.0.0.1 - - [01/Apr/2018 21:21:58] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 21:21:58] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 21:21:58] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 21:21:59] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
127.0.0.1 - - [01/Apr/2018 21:22:40] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 21:22:41] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 21:22:44] "GET /files/Hello%2C%20World%21 HTTP/1.1" 404 -
127.0.0.1 - - [01/Apr/2018 21:27:47] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 21:27:50] "GET /files/ HTTP/1.1" 404 -
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
127.0.0.1 - - [01/Apr/2018 21:34:15] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/cli.py", line 184, in __call__
    self._flush_bg_loading_exception()
  File "/usr/local/lib/python3.5/dist-packages/flask/cli.py", line 172, in _flush_bg_loading_exception
    reraise(*exc_info)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/cli.py", line 161, in _load_app
    self._load_unlocked()
  File "/usr/local/lib/python3.5/dist-packages/flask/cli.py", line 176, in _load_unlocked
    self._app = rv = self.loader()
  File "/usr/local/lib/python3.5/dist-packages/flask/cli.py", line 237, in load_app
    rv = locate_app(self.app_import_path)
  File "/usr/local/lib/python3.5/dist-packages/flask/cli.py", line 90, in locate_app
    __import__(module)
File "/home/shiyanlou/SYL/infomation_site/news/app.py", line 27
    return [ key, value for key,value in a.items() ]
                          ^
SyntaxError: invalid syntax
127.0.0.1 - - [01/Apr/2018 21:34:15] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 21:34:15] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 21:34:15] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 21:34:20] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 21:34:45] "GET / HTTP/1.1" 200 -
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
helloshiyanlou {'title': 'Hello, Shiyanlou!', 'created_time': '2017-09-09 12:00:00', 'content': 'Welcome to shiyanlou.com \\n This is shiyanlou.com louplus demo page. \\n Please let us know if you have any questions \\n Thank you!'}
helloworld {'title': 'Hello, World!', 'created_time': '2017-08-09 12:00:00', 'content': 'Hello world! \\\\n This is hello world demo page. \\\\n Please let us know if you have any questions \\\\n Thank you!'}
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
127.0.0.1 - - [01/Apr/2018 21:36:53] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/shiyanlou/SYL/infomation_site/news/app.py", line 34, in index
    return render_template('index.html',titles = index_html.get_title())
  File "/home/shiyanlou/SYL/infomation_site/news/app.py", line 27, in get_title
    return [ itme['key'] for key,value in a.items() ]
  File "/home/shiyanlou/SYL/infomation_site/news/app.py", line 27, in <listcomp>
    return [ itme['key'] for key,value in a.items() ]
NameError: name 'itme' is not defined
127.0.0.1 - - [01/Apr/2018 21:36:53] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 21:36:53] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 21:36:53] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 21:36:59] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
127.0.0.1 - - [01/Apr/2018 21:37:08] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/shiyanlou/SYL/infomation_site/news/app.py", line 34, in index
    return render_template('index.html',titles = index_html.get_title())
  File "/home/shiyanlou/SYL/infomation_site/news/app.py", line 27, in get_title
    return [ item['key'] for key,value in a.items() ]
  File "/home/shiyanlou/SYL/infomation_site/news/app.py", line 27, in <listcomp>
    return [ item['key'] for key,value in a.items() ]
NameError: name 'item' is not defined
127.0.0.1 - - [01/Apr/2018 21:37:08] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 21:37:08] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 21:37:08] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 21:37:09] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
127.0.0.1 - - [01/Apr/2018 21:37:38] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 21:38:36] "GET /helloshiyanlou HTTP/1.1" 404 -
127.0.0.1 - - [01/Apr/2018 21:38:45] "GET /files/helloshiyanlou HTTP/1.1" 200 -
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
127.0.0.1 - - [01/Apr/2018 21:52:22] "GET /files/helloshiyanlou HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/shiyanlou/SYL/infomation_site/news/app.py", line 44, in file
    return render_template('file.html', url_name = key, value_name = value['title'])
  File "/usr/local/lib/python3.5/dist-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/usr/local/lib/python3.5/dist-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/shiyanlou/SYL/infomation_site/news/templates/file.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/shiyanlou/SYL/infomation_site/news/templates/base.html", line 12, in top-level template code
    <div> {% block contend %} {% endblock %}</div>
  File "/home/shiyanlou/SYL/infomation_site/news/templates/file.html", line 4, in block "contend"
    <h1> {{ file.title }} </h1>
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'file' is undefined
127.0.0.1 - - [01/Apr/2018 21:52:22] "GET /files/helloshiyanlou?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 21:52:22] "GET /files/helloshiyanlou?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 21:52:22] "GET /files/helloshiyanlou?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 21:52:23] "GET /files/helloshiyanlou?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 21:52:23] "GET /files/helloshiyanlou?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 21:55:42] "GET /files/helloshiyanlou HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/shiyanlou/SYL/infomation_site/news/app.py", line 44, in file
    return render_template('file.html', url_name = key, value_name = value['title'])
  File "/usr/local/lib/python3.5/dist-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/usr/local/lib/python3.5/dist-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/shiyanlou/SYL/infomation_site/news/templates/file.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/shiyanlou/SYL/infomation_site/news/templates/base.html", line 12, in top-level template code
    <div> {% block contend %} {% endblock %}</div>
  File "/home/shiyanlou/SYL/infomation_site/news/templates/file.html", line 4, in block "contend"
    <h1> {{ file.title }} </h1>
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'file' is undefined
127.0.0.1 - - [01/Apr/2018 21:55:42] "GET /files/helloshiyanlou?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 21:55:42] "GET /files/helloshiyanlou?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 21:55:42] "GET /files/helloshiyanlou?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 21:55:42] "GET /files/helloshiyanlou?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 21:55:43] "GET /files/helloshiyanlou?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
127.0.0.1 - - [01/Apr/2018 21:56:45] "GET /files/helloshiyanlou HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 21:56:48] "GET / HTTP/1.1" 200 -
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
127.0.0.1 - - [01/Apr/2018 22:18:19] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/shiyanlou/SYL/infomation_site/news/app.py", line 38, in index
    titles_list = values['title']
NameError: name 'values' is not defined
127.0.0.1 - - [01/Apr/2018 22:18:19] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 22:18:19] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 22:18:19] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 22:18:19] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
127.0.0.1 - - [01/Apr/2018 22:18:40] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/shiyanlou/SYL/infomation_site/news/app.py", line 39, in index
    return render_template('index.html', titles = ttiles_list, url = url_name)
NameError: name 'ttiles_list' is not defined
127.0.0.1 - - [01/Apr/2018 22:18:40] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 22:18:40] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 22:18:40] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 22:18:41] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
127.0.0.1 - - [01/Apr/2018 22:18:59] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/shiyanlou/SYL/infomation_site/news/app.py", line 40, in index
    return render_template('index.html', titles = tiles_list, url = url_name)
NameError: name 'tiles_list' is not defined
127.0.0.1 - - [01/Apr/2018 22:18:59] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 22:18:59] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 22:18:59] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 22:19:04] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
127.0.0.1 - - [01/Apr/2018 22:19:13] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/shiyanlou/SYL/infomation_site/news/app.py", line 40, in index
    return render_template('index.html', titles = titles_list, url = url_name)
  File "/usr/local/lib/python3.5/dist-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/shiyanlou/SYL/infomation_site/news/templates/index.html", line 7, in template
    <a href="{{ url_for('file',  = key) }}">{{ title }}</a>
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 896, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 878, in subparse
    rv = self.parse_statement()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 268, in parse_block
    node.body = self.parse_statements(('name:endblock',), drop_needle=True)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 878, in subparse
    rv = self.parse_statement()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 198, in parse_for
    body = self.parse_statements(('name:endfor', 'name:else'))
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 870, in subparse
    add_data(self.parse_tuple(with_condexpr=True))
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 615, in parse_tuple
    args.append(parse())
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 427, in parse_expression
    return self.parse_condexpr()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 432, in parse_condexpr
    expr1 = self.parse_or()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 445, in parse_or
    left = self.parse_and()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 454, in parse_and
    left = self.parse_not()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 465, in parse_not
    return self.parse_compare()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 469, in parse_compare
    expr = self.parse_math1()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 491, in parse_math1
    left = self.parse_concat()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 502, in parse_concat
    args = [self.parse_math2()]
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 512, in parse_math2
    left = self.parse_pow()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 523, in parse_pow
    left = self.parse_unary()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 542, in parse_unary
    node = self.parse_postfix(node)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 671, in parse_postfix
    node = self.parse_call(node)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 785, in parse_call
    args.append(self.parse_expression())
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 427, in parse_expression
    return self.parse_condexpr()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 432, in parse_condexpr
    expr1 = self.parse_or()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 445, in parse_or
    left = self.parse_and()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 454, in parse_and
    left = self.parse_not()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 465, in parse_not
    return self.parse_compare()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 469, in parse_compare
    expr = self.parse_math1()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 491, in parse_math1
    left = self.parse_concat()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 502, in parse_concat
    args = [self.parse_math2()]
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 512, in parse_math2
    left = self.parse_pow()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 523, in parse_pow
    left = self.parse_unary()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 541, in parse_unary
    node = self.parse_primary()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 578, in parse_primary
    self.fail("unexpected '%s'" % describe_token(token), token.lineno)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: unexpected '='
127.0.0.1 - - [01/Apr/2018 22:19:14] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 22:19:14] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 22:19:14] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 22:19:14] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
127.0.0.1 - - [01/Apr/2018 22:20:30] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/shiyanlou/SYL/infomation_site/news/app.py", line 40, in index
    return render_template('index.html', titles = titles_list)
  File "/usr/local/lib/python3.5/dist-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/shiyanlou/SYL/infomation_site/news/templates/index.html", line 7, in template
    <a href="{{ url_for('file',  = key) }}">{{ title }}</a>
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 896, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 878, in subparse
    rv = self.parse_statement()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 268, in parse_block
    node.body = self.parse_statements(('name:endblock',), drop_needle=True)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 878, in subparse
    rv = self.parse_statement()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 198, in parse_for
    body = self.parse_statements(('name:endfor', 'name:else'))
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 870, in subparse
    add_data(self.parse_tuple(with_condexpr=True))
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 615, in parse_tuple
    args.append(parse())
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 427, in parse_expression
    return self.parse_condexpr()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 432, in parse_condexpr
    expr1 = self.parse_or()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 445, in parse_or
    left = self.parse_and()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 454, in parse_and
    left = self.parse_not()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 465, in parse_not
    return self.parse_compare()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 469, in parse_compare
    expr = self.parse_math1()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 491, in parse_math1
    left = self.parse_concat()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 502, in parse_concat
    args = [self.parse_math2()]
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 512, in parse_math2
    left = self.parse_pow()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 523, in parse_pow
    left = self.parse_unary()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 542, in parse_unary
    node = self.parse_postfix(node)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 671, in parse_postfix
    node = self.parse_call(node)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 785, in parse_call
    args.append(self.parse_expression())
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 427, in parse_expression
    return self.parse_condexpr()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 432, in parse_condexpr
    expr1 = self.parse_or()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 445, in parse_or
    left = self.parse_and()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 454, in parse_and
    left = self.parse_not()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 465, in parse_not
    return self.parse_compare()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 469, in parse_compare
    expr = self.parse_math1()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 491, in parse_math1
    left = self.parse_concat()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 502, in parse_concat
    args = [self.parse_math2()]
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 512, in parse_math2
    left = self.parse_pow()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 523, in parse_pow
    left = self.parse_unary()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 541, in parse_unary
    node = self.parse_primary()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 578, in parse_primary
    self.fail("unexpected '%s'" % describe_token(token), token.lineno)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: unexpected '='
127.0.0.1 - - [01/Apr/2018 22:20:30] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 22:20:30] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 22:20:30] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 22:20:31] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
127.0.0.1 - - [01/Apr/2018 22:21:04] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/shiyanlou/SYL/infomation_site/news/app.py", line 39, in index
    return render_template('index.html',titles = titles_list)
  File "/usr/local/lib/python3.5/dist-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/shiyanlou/SYL/infomation_site/news/templates/index.html", line 7, in template
    <a href="{{ url_for('file',  = key) }}">{{ title }}</a>
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 896, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 878, in subparse
    rv = self.parse_statement()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 268, in parse_block
    node.body = self.parse_statements(('name:endblock',), drop_needle=True)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 878, in subparse
    rv = self.parse_statement()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 198, in parse_for
    body = self.parse_statements(('name:endfor', 'name:else'))
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 870, in subparse
    add_data(self.parse_tuple(with_condexpr=True))
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 615, in parse_tuple
    args.append(parse())
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 427, in parse_expression
    return self.parse_condexpr()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 432, in parse_condexpr
    expr1 = self.parse_or()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 445, in parse_or
    left = self.parse_and()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 454, in parse_and
    left = self.parse_not()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 465, in parse_not
    return self.parse_compare()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 469, in parse_compare
    expr = self.parse_math1()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 491, in parse_math1
    left = self.parse_concat()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 502, in parse_concat
    args = [self.parse_math2()]
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 512, in parse_math2
    left = self.parse_pow()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 523, in parse_pow
    left = self.parse_unary()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 542, in parse_unary
    node = self.parse_postfix(node)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 671, in parse_postfix
    node = self.parse_call(node)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 785, in parse_call
    args.append(self.parse_expression())
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 427, in parse_expression
    return self.parse_condexpr()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 432, in parse_condexpr
    expr1 = self.parse_or()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 445, in parse_or
    left = self.parse_and()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 454, in parse_and
    left = self.parse_not()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 465, in parse_not
    return self.parse_compare()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 469, in parse_compare
    expr = self.parse_math1()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 491, in parse_math1
    left = self.parse_concat()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 502, in parse_concat
    args = [self.parse_math2()]
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 512, in parse_math2
    left = self.parse_pow()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 523, in parse_pow
    left = self.parse_unary()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 541, in parse_unary
    node = self.parse_primary()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 578, in parse_primary
    self.fail("unexpected '%s'" % describe_token(token), token.lineno)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: unexpected '='
127.0.0.1 - - [01/Apr/2018 22:21:04] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 22:21:04] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 22:21:05] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 22:21:09] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
127.0.0.1 - - [01/Apr/2018 22:29:06] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/shiyanlou/SYL/infomation_site/news/app.py", line 39, in index
    return render_template('index.html',titles = titles_list)
  File "/usr/local/lib/python3.5/dist-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/shiyanlou/SYL/infomation_site/news/templates/index.html", line 7, in template
    <a href="{{ url_for('file',  = key) }}">{{ title }}</a>
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 896, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 878, in subparse
    rv = self.parse_statement()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 268, in parse_block
    node.body = self.parse_statements(('name:endblock',), drop_needle=True)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 878, in subparse
    rv = self.parse_statement()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 198, in parse_for
    body = self.parse_statements(('name:endfor', 'name:else'))
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 870, in subparse
    add_data(self.parse_tuple(with_condexpr=True))
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 615, in parse_tuple
    args.append(parse())
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 427, in parse_expression
    return self.parse_condexpr()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 432, in parse_condexpr
    expr1 = self.parse_or()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 445, in parse_or
    left = self.parse_and()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 454, in parse_and
    left = self.parse_not()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 465, in parse_not
    return self.parse_compare()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 469, in parse_compare
    expr = self.parse_math1()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 491, in parse_math1
    left = self.parse_concat()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 502, in parse_concat
    args = [self.parse_math2()]
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 512, in parse_math2
    left = self.parse_pow()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 523, in parse_pow
    left = self.parse_unary()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 542, in parse_unary
    node = self.parse_postfix(node)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 671, in parse_postfix
    node = self.parse_call(node)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 785, in parse_call
    args.append(self.parse_expression())
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 427, in parse_expression
    return self.parse_condexpr()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 432, in parse_condexpr
    expr1 = self.parse_or()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 445, in parse_or
    left = self.parse_and()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 454, in parse_and
    left = self.parse_not()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 465, in parse_not
    return self.parse_compare()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 469, in parse_compare
    expr = self.parse_math1()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 491, in parse_math1
    left = self.parse_concat()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 502, in parse_concat
    args = [self.parse_math2()]
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 512, in parse_math2
    left = self.parse_pow()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 523, in parse_pow
    left = self.parse_unary()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 541, in parse_unary
    node = self.parse_primary()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 578, in parse_primary
    self.fail("unexpected '%s'" % describe_token(token), token.lineno)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: unexpected '='
127.0.0.1 - - [01/Apr/2018 22:29:06] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 22:29:11] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 22:29:11] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 22:29:12] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
127.0.0.1 - - [01/Apr/2018 22:32:55] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/shiyanlou/SYL/infomation_site/news/app.py", line 39, in index
    return render_template('index.html',titles = titles_list)
  File "/usr/local/lib/python3.5/dist-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/shiyanlou/SYL/infomation_site/news/templates/index.html", line 7, in template
    <a href="{{ url_for('file',  = key) }}">{{ title }}</a>
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 896, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 878, in subparse
    rv = self.parse_statement()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 268, in parse_block
    node.body = self.parse_statements(('name:endblock',), drop_needle=True)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 878, in subparse
    rv = self.parse_statement()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 198, in parse_for
    body = self.parse_statements(('name:endfor', 'name:else'))
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 870, in subparse
    add_data(self.parse_tuple(with_condexpr=True))
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 615, in parse_tuple
    args.append(parse())
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 427, in parse_expression
    return self.parse_condexpr()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 432, in parse_condexpr
    expr1 = self.parse_or()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 445, in parse_or
    left = self.parse_and()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 454, in parse_and
    left = self.parse_not()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 465, in parse_not
    return self.parse_compare()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 469, in parse_compare
    expr = self.parse_math1()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 491, in parse_math1
    left = self.parse_concat()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 502, in parse_concat
    args = [self.parse_math2()]
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 512, in parse_math2
    left = self.parse_pow()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 523, in parse_pow
    left = self.parse_unary()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 542, in parse_unary
    node = self.parse_postfix(node)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 671, in parse_postfix
    node = self.parse_call(node)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 785, in parse_call
    args.append(self.parse_expression())
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 427, in parse_expression
    return self.parse_condexpr()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 432, in parse_condexpr
    expr1 = self.parse_or()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 445, in parse_or
    left = self.parse_and()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 454, in parse_and
    left = self.parse_not()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 465, in parse_not
    return self.parse_compare()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 469, in parse_compare
    expr = self.parse_math1()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 491, in parse_math1
    left = self.parse_concat()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 502, in parse_concat
    args = [self.parse_math2()]
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 512, in parse_math2
    left = self.parse_pow()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 523, in parse_pow
    left = self.parse_unary()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 541, in parse_unary
    node = self.parse_primary()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 578, in parse_primary
    self.fail("unexpected '%s'" % describe_token(token), token.lineno)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: unexpected '='
127.0.0.1 - - [01/Apr/2018 22:32:55] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 22:33:00] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 22:33:00] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 22:33:01] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
127.0.0.1 - - [01/Apr/2018 22:35:40] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/shiyanlou/SYL/infomation_site/news/app.py", line 39, in index
    return render_template('index.html',titles = titles_list)
  File "/usr/local/lib/python3.5/dist-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/shiyanlou/SYL/infomation_site/news/templates/index.html", line 7, in template
    <a href="{{ url_for('file',  = key) }}">{{ title }}</a>
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 896, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 878, in subparse
    rv = self.parse_statement()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 268, in parse_block
    node.body = self.parse_statements(('name:endblock',), drop_needle=True)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 878, in subparse
    rv = self.parse_statement()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 198, in parse_for
    body = self.parse_statements(('name:endfor', 'name:else'))
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 870, in subparse
    add_data(self.parse_tuple(with_condexpr=True))
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 615, in parse_tuple
    args.append(parse())
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 427, in parse_expression
    return self.parse_condexpr()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 432, in parse_condexpr
    expr1 = self.parse_or()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 445, in parse_or
    left = self.parse_and()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 454, in parse_and
    left = self.parse_not()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 465, in parse_not
    return self.parse_compare()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 469, in parse_compare
    expr = self.parse_math1()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 491, in parse_math1
    left = self.parse_concat()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 502, in parse_concat
    args = [self.parse_math2()]
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 512, in parse_math2
    left = self.parse_pow()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 523, in parse_pow
    left = self.parse_unary()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 542, in parse_unary
    node = self.parse_postfix(node)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 671, in parse_postfix
    node = self.parse_call(node)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 785, in parse_call
    args.append(self.parse_expression())
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 427, in parse_expression
    return self.parse_condexpr()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 432, in parse_condexpr
    expr1 = self.parse_or()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 445, in parse_or
    left = self.parse_and()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 454, in parse_and
    left = self.parse_not()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 465, in parse_not
    return self.parse_compare()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 469, in parse_compare
    expr = self.parse_math1()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 491, in parse_math1
    left = self.parse_concat()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 502, in parse_concat
    args = [self.parse_math2()]
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 512, in parse_math2
    left = self.parse_pow()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 523, in parse_pow
    left = self.parse_unary()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 541, in parse_unary
    node = self.parse_primary()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 578, in parse_primary
    self.fail("unexpected '%s'" % describe_token(token), token.lineno)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: unexpected '='
127.0.0.1 - - [01/Apr/2018 22:35:40] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 22:35:40] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 22:35:40] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 22:35:40] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
127.0.0.1 - - [01/Apr/2018 22:36:43] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/shiyanlou/SYL/infomation_site/news/app.py", line 41, in index
    return render_template('index.html',titles = index_html.get_title())
  File "/usr/local/lib/python3.5/dist-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/shiyanlou/SYL/infomation_site/news/templates/index.html", line 7, in template
    <a href="{{ url_for('file',  = key) }}">{{ title }}</a>
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 896, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 878, in subparse
    rv = self.parse_statement()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 268, in parse_block
    node.body = self.parse_statements(('name:endblock',), drop_needle=True)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 878, in subparse
    rv = self.parse_statement()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 198, in parse_for
    body = self.parse_statements(('name:endfor', 'name:else'))
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 870, in subparse
    add_data(self.parse_tuple(with_condexpr=True))
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 615, in parse_tuple
    args.append(parse())
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 427, in parse_expression
    return self.parse_condexpr()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 432, in parse_condexpr
    expr1 = self.parse_or()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 445, in parse_or
    left = self.parse_and()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 454, in parse_and
    left = self.parse_not()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 465, in parse_not
    return self.parse_compare()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 469, in parse_compare
    expr = self.parse_math1()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 491, in parse_math1
    left = self.parse_concat()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 502, in parse_concat
    args = [self.parse_math2()]
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 512, in parse_math2
    left = self.parse_pow()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 523, in parse_pow
    left = self.parse_unary()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 542, in parse_unary
    node = self.parse_postfix(node)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 671, in parse_postfix
    node = self.parse_call(node)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 785, in parse_call
    args.append(self.parse_expression())
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 427, in parse_expression
    return self.parse_condexpr()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 432, in parse_condexpr
    expr1 = self.parse_or()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 445, in parse_or
    left = self.parse_and()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 454, in parse_and
    left = self.parse_not()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 465, in parse_not
    return self.parse_compare()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 469, in parse_compare
    expr = self.parse_math1()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 491, in parse_math1
    left = self.parse_concat()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 502, in parse_concat
    args = [self.parse_math2()]
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 512, in parse_math2
    left = self.parse_pow()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 523, in parse_pow
    left = self.parse_unary()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 541, in parse_unary
    node = self.parse_primary()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 578, in parse_primary
    self.fail("unexpected '%s'" % describe_token(token), token.lineno)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: unexpected '='
127.0.0.1 - - [01/Apr/2018 22:36:43] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 22:36:43] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 22:36:43] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 22:36:43] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
127.0.0.1 - - [01/Apr/2018 22:37:39] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/shiyanlou/SYL/infomation_site/news/app.py", line 41, in index
    return render_template('index.html',titles = index_html.get_title())
  File "/usr/local/lib/python3.5/dist-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/shiyanlou/SYL/infomation_site/news/templates/index.html", line 7, in template
    <a href="{{ url_for('file',  = key) }}">{{ title }}</a>
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 896, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 878, in subparse
    rv = self.parse_statement()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 268, in parse_block
    node.body = self.parse_statements(('name:endblock',), drop_needle=True)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 878, in subparse
    rv = self.parse_statement()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 198, in parse_for
    body = self.parse_statements(('name:endfor', 'name:else'))
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 870, in subparse
    add_data(self.parse_tuple(with_condexpr=True))
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 615, in parse_tuple
    args.append(parse())
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 427, in parse_expression
    return self.parse_condexpr()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 432, in parse_condexpr
    expr1 = self.parse_or()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 445, in parse_or
    left = self.parse_and()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 454, in parse_and
    left = self.parse_not()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 465, in parse_not
    return self.parse_compare()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 469, in parse_compare
    expr = self.parse_math1()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 491, in parse_math1
    left = self.parse_concat()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 502, in parse_concat
    args = [self.parse_math2()]
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 512, in parse_math2
    left = self.parse_pow()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 523, in parse_pow
    left = self.parse_unary()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 542, in parse_unary
    node = self.parse_postfix(node)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 671, in parse_postfix
    node = self.parse_call(node)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 785, in parse_call
    args.append(self.parse_expression())
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 427, in parse_expression
    return self.parse_condexpr()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 432, in parse_condexpr
    expr1 = self.parse_or()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 445, in parse_or
    left = self.parse_and()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 454, in parse_and
    left = self.parse_not()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 465, in parse_not
    return self.parse_compare()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 469, in parse_compare
    expr = self.parse_math1()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 491, in parse_math1
    left = self.parse_concat()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 502, in parse_concat
    args = [self.parse_math2()]
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 512, in parse_math2
    left = self.parse_pow()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 523, in parse_pow
    left = self.parse_unary()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 541, in parse_unary
    node = self.parse_primary()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 578, in parse_primary
    self.fail("unexpected '%s'" % describe_token(token), token.lineno)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: unexpected '='
127.0.0.1 - - [01/Apr/2018 22:37:39] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 22:37:39] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 22:37:39] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 22:37:44] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 22:38:24] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/shiyanlou/SYL/infomation_site/news/app.py", line 41, in index
    return render_template('index.html',titles = index_html.get_title())
  File "/usr/local/lib/python3.5/dist-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/usr/local/lib/python3.5/dist-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/shiyanlou/SYL/infomation_site/news/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/shiyanlou/SYL/infomation_site/news/templates/base.html", line 12, in top-level template code
    <div> {% block contend %} {% endblock %}</div>
  File "/home/shiyanlou/SYL/infomation_site/news/templates/index.html", line 7, in block "contend"
    <a href="{{ url_for('file', a = key) }}">{{ title }}</a>
  File "/usr/local/lib/python3.5/dist-packages/flask/helpers.py", line 333, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1805, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/helpers.py", line 323, in url_for
    force_external=external)
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/routing.py", line 1768, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'file' with values ['a']. Did you forget to specify values ['filename']?
127.0.0.1 - - [01/Apr/2018 22:38:25] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 22:38:25] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 22:38:25] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 22:38:29] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
127.0.0.1 - - [01/Apr/2018 22:39:33] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 22:39:43] "GET /files/ HTTP/1.1" 404 -
127.0.0.1 - - [01/Apr/2018 22:39:47] "GET /files/ HTTP/1.1" 404 -
127.0.0.1 - - [01/Apr/2018 22:39:50] "GET /files/ HTTP/1.1" 404 -
127.0.0.1 - - [01/Apr/2018 22:39:53] "GET /files/ HTTP/1.1" 404 -
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
127.0.0.1 - - [01/Apr/2018 22:41:38] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/cli.py", line 184, in __call__
    self._flush_bg_loading_exception()
  File "/usr/local/lib/python3.5/dist-packages/flask/cli.py", line 172, in _flush_bg_loading_exception
    reraise(*exc_info)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/cli.py", line 161, in _load_app
    self._load_unlocked()
  File "/usr/local/lib/python3.5/dist-packages/flask/cli.py", line 176, in _load_unlocked
    self._app = rv = self.loader()
  File "/usr/local/lib/python3.5/dist-packages/flask/cli.py", line 237, in load_app
    rv = locate_app(self.app_import_path)
  File "/usr/local/lib/python3.5/dist-packages/flask/cli.py", line 90, in locate_app
    __import__(module)
File "/home/shiyanlou/SYL/infomation_site/news/app.py", line 42
    a = files.get_json_content()
    ^
IndentationError: expected an indented block
127.0.0.1 - - [01/Apr/2018 22:41:39] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 22:41:39] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 22:41:39] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 22:41:39] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 22:41:59] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 22:42:02] "GET /files/ HTTP/1.1" 404 -
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
127.0.0.1 - - [01/Apr/2018 22:52:53] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 22:52:55] "GET /files/ HTTP/1.1" 404 -
127.0.0.1 - - [01/Apr/2018 22:53:04] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 22:53:06] "GET /files/ HTTP/1.1" 404 -
127.0.0.1 - - [01/Apr/2018 22:54:34] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 22:54:39] "GET /files/Hello%2C%20World%21 HTTP/1.1" 404 -
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
127.0.0.1 - - [01/Apr/2018 23:04:32] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 23:04:34] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 23:04:35] "GET / HTTP/1.1" 200 -
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
127.0.0.1 - - [01/Apr/2018 23:05:25] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 23:05:28] "GET /files/Hello%2C%20Shiyanlou%21 HTTP/1.1" 404 -
127.0.0.1 - - [01/Apr/2018 23:06:12] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 23:06:20] "GET /files/%5B%27helloshiyanlou%27%2C%20%27helloworld%27%5D HTTP/1.1" 404 -
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
127.0.0.1 - - [01/Apr/2018 23:07:39] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 23:07:57] "GET /files/helloshiyanlou HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 23:08:01] "GET /files/Hello%2C%20Shiyanlou%21 HTTP/1.1" 404 -
127.0.0.1 - - [01/Apr/2018 23:08:59] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 23:09:38] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 23:09:39] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 23:10:12] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 23:10:30] "GET /files/helloworld HTTP/1.1" 200 -
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
127.0.0.1 - - [01/Apr/2018 23:23:32] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/cli.py", line 184, in __call__
    self._flush_bg_loading_exception()
  File "/usr/local/lib/python3.5/dist-packages/flask/cli.py", line 172, in _flush_bg_loading_exception
    reraise(*exc_info)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/cli.py", line 161, in _load_app
    self._load_unlocked()
  File "/usr/local/lib/python3.5/dist-packages/flask/cli.py", line 176, in _load_unlocked
    self._app = rv = self.loader()
  File "/usr/local/lib/python3.5/dist-packages/flask/cli.py", line 237, in load_app
    rv = locate_app(self.app_import_path)
  File "/usr/local/lib/python3.5/dist-packages/flask/cli.py", line 90, in locate_app
    __import__(module)
File "/home/shiyanlou/SYL/infomation_site/news/app.py", line 39
    def file(filename):
      ^
SyntaxError: invalid syntax
127.0.0.1 - - [01/Apr/2018 23:23:32] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 23:23:32] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 23:23:32] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 23:23:33] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 23:26:26] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 23:26:28] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 23:27:08] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 23:27:12] "GET /files/helloworld HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 23:27:15] "GET /files/helloshiyanlou HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 23:27:43] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 23:28:03] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 23:28:07] "GET /files/helloworld HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2018 23:28:12] "GET /files/helloshiyanlou HTTP/1.1" 200 -
 * Detected change in '/home/shiyanlou/SYL/infomation_site/news/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 258-572-018
